name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: dotnet ${{ matrix.dotnet }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        dotnet: ['2.2.103']
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - run: dotnet build --configuration "Release" --output ./release

    - name: Run tests
      run: dotnet test
    
    - name: Publish package
      if: matrix.os == 'windows-latest'
      env:
        PACKAGE_REGISTRY_USERNAME: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}
        PACKAGE_REGISTRY_PASSWORD: ${{ secrets.PACKAGE_REGISTRY_PASSWORD }}
      run: ./nuget/publish.bat
      