name: Publish Package

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish Packages
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'

    - run: dotnet build --configuration "Release"

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Add Nuget Source
      run: nuget source Add -Name "GitHub - erictuvesson" -Source "https://nuget.pkg.github.com/erictuvesson/index.json" -UserName ${{ secrets.PACKAGE_REGISTRY_USERNAME }} -Password ${{ secrets.PACKAGE_REGISTRY_PASSWORD }}

    - name: Nuget Push
      run: nuget push d://a/OpenInput/OpenInput/build/*.nupkg -Source "GitHub - erictuvesson"

    - name: Nuget Push Symbols
      run: nuget push d://a/OpenInput/OpenInput/build/*.snupkg -Source "GitHub - erictuvesson"
