name: CI

on: [pull_request]

jobs:
  build:
    name: dotnet ${{ matrix.dotnet }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        dotnet: ['2.2.103']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - run: dotnet build
    
    - name: Run tests
      run: dotnet test
    
